# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdb8d0e22f9274280f8577228f0c2d8808c789b742009361d903ea91124814c912a34895697b5614816c0249d78efa273cfd626aecb7b365812a2295ed4bf48b

test:
  secret_key_base: e0b128c559c6de84e6b82477adf9818ae89432463a04480519460f85351b5163930a096305d4a5ce2bdb886f36c5b6c8443a13da62e1a9dfc4faf1fd3207d872

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
